# Generated by Django 2.2.14 on 2020-07-22 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geonode_themes', '0010_auto_20200115_1121'),
    ]

    operations = [
        migrations.CreateModel(
            name='ADBPOJumbotronSlideShow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slide_name', models.CharField(max_length=255, unique=True)),
                ('jumbotron_slide_image', models.ImageField(blank=True, null=True, upload_to='img/%Y/%m', verbose_name='Jumbotron slide background')),
                ('jumbotron_slide_content', models.TextField(blank=True, null=True, verbose_name='Jumbotron slide content')),
                ('hide_jumbotron_slide_content', models.BooleanField(default=False, help_text='Check this if the jumbotron background image already contains text', verbose_name='Hide text in the jumbotron slide')),
                ('is_enabled', models.BooleanField(default=True, help_text='Disabling this slide will hide it from the slide show')),
            ],
        ),
        migrations.CreateModel(
            name='ADBPOCustomGeonodeTheme',
            fields=[
                ('geonodethemecustomization_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='geonode_themes.GeoNodeThemeCustomization')),
                ('jumbotron_slide_show', models.ManyToManyField(blank=True, to='themes.ADBPOJumbotronSlideShow')),
            ],
            bases=('geonode_themes.geonodethemecustomization',),
        ),
    ]
