# Generated by Django 2.2.14 on 2020-07-29 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0043_auto_20200527_0833'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('menuitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.MenuItem')),
                ('icon', models.ImageField(upload_to='img/%Y/%m', verbose_name='Icon Image')),
                ('is_enabled', models.BooleanField(default=True, help_text='Disabling this will hide the link from the home page quick filter links')),
            ],
            bases=('base.menuitem',),
        ),
    ]
